cluster_name = "aws-eks-cluster1"
node_name = "aws-eks-node-dev"
aws_region = "us-east-2"
instance_type = "t2.micro"
domain_name= "*.ja50n.com"
hosted_zone_id = ""
hosted_zone_url = ""
environment = "dev"