serviceType: ClusterIP
ghostHost: ghost.kumpf.mobi
ingress:
  enabled: true
  hosts:
    - name: ghost.kumpf.mobi
      tls: true
      tlsSecret: ghost-app-tls
      annotations:
        kubernetes.io/ingress.class: nginx
        kubernetes.io/tls-acme: "true"
mariadb:
  replication:
    enabled: true
